CREATE VIEW VW_SYS_MENU AS 
WITH TG (
	MENU_IDX, 
	MENU_NM, 
	UP_MENU_IDX, 
	MENU_LV, 
	SORT_PATH,
	MENU_NIX,
	MENU_LINK,
	MENU_ORD,
	MENU_IMG_PATH,
	LEFT_IMG_PATH,
	TITLE_IMG_PATH,
	SITEMAP_IMG_PATH,
	INFO01_IMG_PATH,
	INFO02_IMG_PATH,
	BLANK_YN,
	TABMENU_YN,
	MEMMENU_YN,
	USE_YN,
	MU_GUB,
	MU_SITE,
	MU_LANG,						
	OWN_INFO,
	WRITER,
	WDT,
	MODIFIER,
	MDT	
) AS 
(
	SELECT 
		MENU_IDX, 
		MENU_NM, 
		UP_MENU_IDX, 
		1 AS MENU_LV,  
		CAST('/' + RIGHT('000000' + CONVERT(VARCHAR, MENU_ORD), 6) AS VARCHAR(MAX)),
		MENU_NIX,
		MENU_LINK,
		MENU_ORD,
		MENU_IMG_PATH,
		LEFT_IMG_PATH,
		TITLE_IMG_PATH,
		SITEMAP_IMG_PATH,
		INFO01_IMG_PATH,
		INFO02_IMG_PATH,
		BLANK_YN,
		TABMENU_YN,
		MEMMENU_YN,
		USE_YN,
		MU_GUB,
		MU_SITE,
		MU_LANG,						
		OWN_INFO,
		WRITER,
		WDT,
		MODIFIER,
		MDT			
	FROM CMS_SYS_MENU
	WHERE 
		UP_MENU_IDX IS NULL OR UP_MENU_IDX = ''
	UNION ALL
	SELECT 
		CHILD.MENU_IDX, 
		CHILD.MENU_NM, 
		CHILD.UP_MENU_IDX, 
		TG.MENU_LV + 1 AS MENU_LV,
		TG.SORT_PATH + '/' + RIGHT('000000' + CONVERT(VARCHAR, CHILD.MENU_ORD), 6),
		CHILD.MENU_NIX,
		CHILD.MENU_LINK,
		CHILD.MENU_ORD,
		CHILD.MENU_IMG_PATH,
		CHILD.LEFT_IMG_PATH,
		CHILD.TITLE_IMG_PATH,
		CHILD.SITEMAP_IMG_PATH,
		CHILD.INFO01_IMG_PATH,
		CHILD.INFO02_IMG_PATH,
		CHILD.BLANK_YN,
		CHILD.TABMENU_YN,
		CHILD.MEMMENU_YN,
		CHILD.USE_YN,
		CHILD.MU_GUB,
		CHILD.MU_SITE,
		CHILD.MU_LANG,						
		CHILD.OWN_INFO,
		CHILD.WRITER,
		CHILD.WDT,
		CHILD.MODIFIER,
		CHILD.MDT			
	FROM 
		CMS_SYS_MENU AS CHILD, 
		TG
	WHERE 
		TG.MENU_IDX = CHILD.UP_MENU_IDX
)
SELECT 
	MENU_IDX, 
	MENU_NM, 
	MENU_LV, 
	SORT_PATH,
	UP_MENU_IDX,
	CASE (SELECT COUNT(*) FROM CMS_SYS_MENU WHERE UP_MENU_IDX = TG.MENU_IDX) 
		WHEN 0 THEN 1
		ELSE 0
	END AS IS_LEAF,
	MENU_NIX,
	MENU_LINK,
	MENU_ORD,
	MENU_IMG_PATH,
	LEFT_IMG_PATH,
	TITLE_IMG_PATH,
	SITEMAP_IMG_PATH,
	INFO01_IMG_PATH,
	INFO02_IMG_PATH,
	BLANK_YN,
	TABMENU_YN,
	MEMMENU_YN,
	USE_YN,
	MU_GUB,
	MU_SITE,
	MU_LANG,						
	OWN_INFO,
	WRITER,
	WDT,
	MODIFIER,
	MDT		
FROM TG;











CREATE VIEW dbo.VW_PLANI_RAND
AS
SELECT CAST(floor(rand() * 100) as int) AS RNDVAL